# Generated by Django 5.0.3 on 2024-04-02 07:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField(validators=[django.core.validators.MaxValueValidator(150)])),
                ('nota', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
            ],
        ),
    ]
