# Generated by Django 5.0.3 on 2024-04-02 06:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(150)]),
        ),
    ]
