# Generated by Django 5.0.3 on 2024-04-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0003_alter_estudiante_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='mail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Legajo'),
        ),
    ]
